//Авторизация
export const AUTH_REQUEST = 'REGISTER_REQUEST';
export const AUTH_FAILED = 'REGISTER_FAILED';
export const AUTH_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR';

export const AUTH_SET_NEW_TOKEN = 'AUTH_SET_NEW_TOKEN';

export const AUTH_SET_USER_INFO = 'AUTH_SET_USER_INFO';

//Выход из системы
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED';

//Обновление данных пользователя
export const AUTH_UPDATE_REQUEST = 'AUTH_UPDATE_REQUEST';
export const AUTH_UPDATE_SUCCESS = 'AUTH_UPDATE_SUCCESS';
export const AUTH_UPDATE_FAILED = 'AUTH_UPDATE_FAILED';

//Заказ
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

//Игредиенты 
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT';

export const CLEAR_ALL_INGREDIENTS = 'CLEAR_ALL_INGREDIENTS';

export const ADD_TO_CONSTRUCTOR = 'ADD_TO_CONSTRUCTOR';
export const DELETE_FROM_CONSTRUCTOR = 'DELETE_FROM_CONSTRUCTOR';
export const DELETE_ALL_FROM_CONSTRUCTOR = 'DELETE_ALL_FROM_CONSTRUCTOR';

export const MOVE_INGREDIENTS_CONSTRUCTOR = 'MOVE_INGREDIENTS_CONSTRUCTOR';