export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const INCREASE_INGREDIENT: 'INCREASE_INGREDIENT' = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT: 'DECREASE_INGREDIENT' = 'DECREASE_INGREDIENT';

export const CLEAR_ALL_INGREDIENTS: 'CLEAR_ALL_INGREDIENTS' = 'CLEAR_ALL_INGREDIENTS';

export const ADD_TO_CONSTRUCTOR: 'ADD_TO_CONSTRUCTOR' = 'ADD_TO_CONSTRUCTOR';
export const DELETE_FROM_CONSTRUCTOR: 'DELETE_FROM_CONSTRUCTOR' = 'DELETE_FROM_CONSTRUCTOR';
export const DELETE_ALL_FROM_CONSTRUCTOR: 'DELETE_ALL_FROM_CONSTRUCTOR' = 'DELETE_ALL_FROM_CONSTRUCTOR';

export const MOVE_INGREDIENTS_CONSTRUCTOR: 'MOVE_INGREDIENTS_CONSTRUCTOR' = 'MOVE_INGREDIENTS_CONSTRUCTOR';