export const WS_INIT_AUTH = 'WS_INIT_AUTH';
export const WS_SEND_MESSAGE_AUTH = 'WS_SEND_MESSAGE_AUTH';
export const WS_ON_CLOSE_AUTH = 'WS_ON_CLOSE_AUTH';
export const WS_CLOSE_CONNECTION_AUTH = 'WS_CLOSE_CONNECTION_AUTH';
export const WS_ON_OPEN_AUTH = 'WS_ON_OPEN_AUTH';
export const WS_ON_ERROR_AUTH = 'WS_ON_ERROR_AUTH';
export const WS_ON_MESSAGE_AUTH = 'WS_ON_MESSAGE_AUTH';