export const WS_INIT: 'WS_INIT' = 'WS_INIT';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_ON_CLOSE: 'WS_ON_CLOSE' = 'WS_ON_CLOSE';
export const WS_CLOSE_CONNECTION: 'WS_CLOSE_CONNECTION' = 'WS_CLOSE_CONNECTION';
export const WS_ON_OPEN: 'WS_ON_OPEN' = 'WS_ON_OPEN';
export const WS_ON_ERROR: 'WS_ON_ERROR' = 'WS_ON_ERROR';
export const WS_ON_MESSAGE: 'WS_ON_MESSAGE' = 'WS_ON_MESSAGE';